# Generated by Django 4.1 on 2025-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('paciente', models.CharField(max_length=250)),
                ('tiempo', models.IntegerField()),
                ('medico', models.CharField(max_length=250)),
                ('cita', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
